name: Backend Continuous Integration

run:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  linting-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repository
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependency
        run: |
          cd starter/backend
          pip install pipenv flake8
          pipenv install --dev

      - name: Run linting-job
        run: |
          cd starter/backend
          pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repository
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependency
        run: |
          cd starter/backend
          pip install pipenv flake8
          pipenv install --dev

      - name: Run test
        run: |
          cd starter/backend
          pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [linting-job, test]

    steps:
      - name: Check the repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
            cd starter/backend
            docker build --tag mp-backend:latest .

