name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  linting-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repository
        uses: actions/checkout@v3

      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependency
        run: |
          cd starter/frontend
          npm install

      - name: Run linting-job
        run: |
          cd starter/frontend
          npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repository
        uses: actions/checkout@v3

      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependency
        run: |
          cd starter/frontend
          npm install

      - name: Run test
        run: |
          cd starter/frontend
          npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [linting-job, test]

    steps:
      - name: Check the repository
        uses: actions/checkout@v3

      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependency
        run: |
          cd starter/frontend
          npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          cd starter/frontend
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_FRONTEND }}:${GITHUB_SHA} .

      - name: Login to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Push Docker image to ECR
        run: |
          cd starter/frontend
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_FRONTEND }}:${GITHUB_SHA}

      - name: Update kebeconfig to access EKS
        run:
          aws eks update-kubeconfig --name cluster --region ${{ secrets.AWS_REGION }}

      - name: Deploy to Kubernetes
        run:
          cd ./starter/frontend/k8s &&
          kustomize edit set image backend=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_FRONTEND }}:${GITHUB_SHA} &&
          kustomize build | kubectl apply -f -


