name: Frontend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  linting-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repository
        uses: actions/checkout@v4

      - name: Setup Node environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependency
        run: |
          cd stater/frontend
          npm install

      - name: Run linting-job
        run: |
          cd starter/frontend
          npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repository
        uses: actions/checkout@v3

      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependency
        run: |
          cd stater/frontend
          npm install

      - name: Run test
        run: |
          cd starter/frontend
          npm run test

  build:
    runs-on: ubuntu-latest
    needs: [linting-job, test]

    steps:
      - name: Check the repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          cd starter/frontend
          docker build --tag mp-backend:latest .





